import { SliceZone } from '@prismicio/react'

import { createClient } from '../services/prismic'
import { components } from '../../slices'
import { BlogPost } from '../types/prismic'
import Header from '../components/header'
import Posts from '../components/posts'
import { getBlogPosts } from '../utils/getPrismicData'
import Head from 'next/head'
import { useState } from 'react'


type Props = {
  blogPosts: BlogPost[];
}

const Page = ({ blogPosts } : Props ) => {
  

  return(
  <>
    <Head>
      <title>Spacetraveling</title>
      <meta name='description' content='Generated by create next app'/>
    </Head>
    <Header />
    <Posts data={blogPosts}  />
  </>
  )
}

export default Page

export async function getStaticProps({ previewData }) {

  const blogPosts = await (await getBlogPosts(1,previewData));
  return {
    props: {
      blogPosts
    },
  }
}





